# Generated by Django 5.2.7 on 2025-10-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='rotation_interval',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
