# Generated by Django 5.2.7 on 2025-10-18 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_shift_duration_hours_remove_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='rotation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonar',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
