# Generated by Django 5.2.7 on 2025-10-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_employeeassignment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sonar',
            name='max_employees',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WeeklyShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
        ),
    ]
