# Generated by Django 5.2.7 on 2025-10-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_employee_is_on_leave_sonar_max_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftassignment',
            name='employee',
        ),
        migrations.AddField(
            model_name='weeklyshiftassignment',
            name='employees',
            field=models.ManyToManyField(to='shifts.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(choices=[('morning', 'صباحي'), ('evening', 'مسائي'), ('night', 'ليلي')], max_length=20, unique=True),
        ),
    ]
