# Generated by Django 5.2.7 on 2025-10-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_weeklyshiftassignment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftassignment',
            name='week_end_date',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftassignment',
            name='week_start_date',
        ),
    ]
