# Generated by Django 5.2.7 on 2025-10-19 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_weeklyshiftassignment_week_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyshiftassignment',
            name='week_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weeklyshiftassignment',
            name='week_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
