# Generated by Django 4.2.11 on 2025-10-20 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0008_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'إسناد موظف', 'verbose_name_plural': 'إسنادات الموظفين'},
        ),
        migrations.CreateModel(
            name='ConfirmedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التأكيد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التأكيد بواسطة')),
                ('employee_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='shifts.employeeassignment')),
            ],
            options={
                'verbose_name': 'تبديل مؤكد',
                'verbose_name_plural': 'التبديلات المؤكدة',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
