# Generated by Django 4.2.11 on 2025-10-20 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0009_alter_employeeassignment_options_confirmedassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('rejected', 'مرفوض')], max_length=20, verbose_name='الحالة')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التأكيد/الرفض')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='shifts.employeeassignment', verbose_name='التبديل')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التأكيد/الرفض بواسطة')),
            ],
            options={
                'verbose_name': 'تأكيد تبديل',
                'verbose_name_plural': 'تأكيدات التبديلات',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConfirmedAssignment',
        ),
    ]
