# Generated by Django 4.2.11 on 2025-10-20 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0010_assignmentconfirmation_delete_confirmedassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_interval_hours', models.FloatField(default=3.0, help_text='مثال: 2.5 = كل ساعتين ونصف', verbose_name='فترة التبديل (بالساعات)')),
                ('early_notification_minutes', models.IntegerField(default=30, help_text='كم دقيقة قبل التبديل الفعلي يتم إرسال الإشعار', verbose_name='الإشعار المبكر (بالدقائق)')),
                ('is_rotation_active', models.BooleanField(default=True, verbose_name='تفعيل التبديل التلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
