# Generated by Django 4.2.11 on 2025-10-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('notification_type', models.CharField(choices=[('admin', 'إدمن'), ('employee', 'موظف')], max_length=20, verbose_name='نوع الإشعار')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_notifications', to='shifts.employeeassignment', verbose_name='التبديل')),
            ],
            options={
                'verbose_name': 'إشعار مبكر',
                'verbose_name_plural': 'الإشعارات المبكرة',
                'unique_together': {('assignment', 'notification_type')},
            },
        ),
    ]
