# Generated by Django 4.2.11 on 2025-10-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_alter_employee_options_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='assigned_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='shifts.shift', verbose_name='الشفت المسؤول عنه'),
        ),
    ]
