# Generated by Django 4.2.11 on 2025-10-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0014_supervisor_assigned_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='employee_confirmed',
            field=models.BooleanField(default=False, verbose_name='تأكيد الموظف'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='employee_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تأكيد الموظف'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor_confirmed',
            field=models.BooleanField(default=False, verbose_name='تأكيد المشرف'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تأكيد المشرف'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المؤكد'),
        ),
    ]
