# Generated by Django 4.2.11 on 2025-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_employeeassignment_employee_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earlynotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='earlynotification',
            name='minutes_before',
            field=models.IntegerField(default=30, verbose_name='الدقائق المتبقية عند الإرسال'),
        ),
        migrations.AddField(
            model_name='earlynotification',
            name='notification_stage',
            field=models.CharField(choices=[('initial', 'إشعار أولي (30 دقيقة)'), ('reminder', 'تذكير (كل 10 دقائق)'), ('final', 'إشعار نهائي (وقت التبديل)')], default='initial', max_length=20, verbose_name='مرحلة الإشعار'),
        ),
    ]
