# Generated by Django 4.2.11 on 2025-10-21 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0016_add_notification_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='إرسال لجميع الموظفين')),
                ('total_sent', models.IntegerField(default=0, verbose_name='عدد المرسل إليهم')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('target_employees', models.ManyToManyField(blank=True, help_text='اترك فارغاً للإرسال لجميع الموظفين', to='shifts.employee', verbose_name='الموظفون المستهدفون')),
            ],
            options={
                'verbose_name': 'إشعار مخصص',
                'verbose_name_plural': 'الإشعارات المخصصة',
                'ordering': ['-sent_at'],
            },
        ),
    ]
