# Generated by Django 4.2.11 on 2025-10-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0017_add_custom_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='last_rotation_time',
            field=models.DateTimeField(blank=True, help_text='آخر وقت تم فيه تنفيذ التبديل التلقائي', null=True, verbose_name='آخر وقت تبديل'),
        ),
    ]
