# Generated by Django 4.2.11 on 2025-10-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_systemsettings_last_rotation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlynotification',
            name='notification_stage',
            field=models.CharField(choices=[('initial', 'إشعار أولي (30 دقيقة)'), ('reminder', 'تذكير (كل 10 دقائق)'), ('final', 'إشعار نهائي (وقت التبديل)'), ('unconfirmed_warning', 'تحذير: لم يؤكد الموظف')], default='initial', max_length=30, verbose_name='مرحلة الإشعار'),
        ),
    ]
