# Generated by Django 4.2.11 on 2025-10-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0019_update_notification_stage_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='is_expired_unconfirmed',
            field=models.BooleanField(default=False, verbose_name='منتهي غير مؤكد'),
        ),
    ]
