# Generated by Django 4.2.11 on 2025-10-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0020_employeeassignment_expired_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='is_expired_unconfirmed',
        ),
        migrations.AddField(
            model_name='employee',
            name='consecutive_rest_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات الراحة المتتالية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_work_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر وقت عمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_work_hours',
            field=models.FloatField(default=0.0, verbose_name='إجمالي ساعات العمل'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='is_standby',
            field=models.BooleanField(default=False, verbose_name='في حالة احتياط'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='work_duration_hours',
            field=models.FloatField(default=0.0, verbose_name='مدة العمل بالساعات'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='sonar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.sonar'),
        ),
    ]
