# Generated by Django 5.2.7 on 2025-10-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0021_fair_rotation_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='rotation_interval_hours',
            field=models.FloatField(default=3.0, help_text='🔒 القيمة ثابتة: 3 ساعات (لا يمكن تغييرها من الواجهة)', verbose_name='فترة التبديل (بالساعات) - ثابتة'),
        ),
    ]
