# Generated by Django 4.2.11 on 2025-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0022_alter_systemsettings_rotation_interval_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkHoursReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('reset_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصفير')),
                ('total_employees', models.IntegerField(default=0, verbose_name='عدد الموظفين')),
                ('total_hours_before_reset', models.FloatField(default=0.0, verbose_name='إجمالي الساعات قبل التصفير')),
                ('average_hours_before_reset', models.FloatField(default=0.0, verbose_name='متوسط الساعات قبل التصفير')),
            ],
            options={
                'verbose_name': 'سجل تصفير شهري',
                'verbose_name_plural': 'سجلات التصفير الشهرية',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
