# Generated by Django 4.2.11 on 2025-10-25 04:31

from django.db import migrations


def fix_rotation_interval(apps, schema_editor):
    """إصلاح قيمة rotation_interval_hours إلى 3.0 ساعات"""
    SystemSettings = apps.get_model('shifts', 'SystemSettings')
    
    # تحديث جميع الإعدادات الموجودة
    SystemSettings.objects.all().update(rotation_interval_hours=3.0)
    
    # إذا لم يكن هناك إعدادات، إنشاء واحدة
    if not SystemSettings.objects.exists():
        SystemSettings.objects.create(
            rotation_interval_hours=3.0,
            early_notification_minutes=30,
            is_rotation_active=True
        )


def reverse_fix(apps, schema_editor):
    """لا شيء - لا نريد الرجوع إلى القيمة الخاطئة"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0023_monthly_reset'),
    ]

    operations = [
        migrations.RunPython(fix_rotation_interval, reverse_fix),
    ]
